"""Import eBible KJV HTML speech markup; never modify the bundled Scripture text.
Usage: python3 tools/integrity/import_red_letters.py /path/to/eng-kjv_html.zip
Only exact, ordered phrase matches are accepted. Unmatched markup is reported.
"""
import hashlib, json, re, sys, zipfile
from pathlib import Path
from html.parser import HTMLParser
CODES = dict(zip('GEN EXO LEV NUM DEU JOS JDG RUT 1SA 2SA 1KI 2KI 1CH 2CH EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZK DAN HOS JOL AMO OBA JON MIC NAM HAB ZEP HAG ZEC MAL MAT MRK LUK JHN ACT ROM 1CO 2CO GAL EPH PHP COL 1TH 2TH 1TI 2TI TIT PHM HEB JAS 1PE 2PE 1JN 2JN 3JN JUD REV'.split(), ['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalms','Proverbs','Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation']))
class Markup(HTMLParser):
    def __init__(self):
        super().__init__(); self.stack=[]; self.verse=None; self.parts={}; self.active=None
    def handle_starttag(self,tag,attrs):
        attrs=dict(attrs)
        if tag=='span':
            cls=attrs.get('class',''); self.stack.append(cls)
            if cls=='verse':
                m=re.fullmatch(r'V(\d+)',attrs.get('id',''))
                if m: self.verse=int(m[1])
            if cls=='wj':
                self.active=[]
                if self.verse is not None:self.parts.setdefault(self.verse,[]).append(self.active)
    def handle_endtag(self,tag):
        if tag=='span' and self.stack:
            cls=self.stack.pop()
            if cls=='wj':self.active=None
    def handle_data(self,data):
        if self.active is not None and 'verse' not in self.stack and not any(c in self.stack for c in ['notemark','ft','note']):
            self.active.append(data)
def fingerprint(text):
    n=0
    for ch in text: n=(n*31+ord(ch)) & 0x7fffffff
    return n
archive=Path(sys.argv[1]); z=zipfile.ZipFile(archive)
books={b['name']:b for b in json.loads(Path('assets/bible/kjv.json').read_text())['books']}
result={}; unmatched=[]; phrases=0
for fn in sorted(z.namelist()):
    m=re.fullmatch(r'([A-Z0-9]{3})(\d+)\.htm',fn)
    if not m or m[1] not in CODES:continue
    name=CODES[m[1]]; chapter=int(m[2]); parser=Markup();parser.feed(z.read(fn).decode('utf-8-sig'))
    for verse,parts in parser.parts.items():
        text=books[name]['chapters'][chapter-1]['verses'][verse-1]['text'].strip()
        spans=[]; cursor=0
        for part in parts:
            phrase=re.sub(r'\s+',' ',''.join(part).replace('¶', '')).strip()
            if not phrase:continue
            phrases+=1; start=text.find(phrase,cursor)
            if start<0:
                unmatched.append({'reference':f'{name} {chapter}:{verse}','speech':phrase});spans=[];break
            spans.extend([start,start+len(phrase)]);cursor=start+len(phrase)
        if spans:result[f'{name}:{chapter}:{verse}']=[fingerprint(text),*spans]
Path('lib/data/red_letter_spans.dart').write_text('// GENERATED by tools/integrity/import_red_letters.py. See content review report.\nconst redLetterSpans = <String, List<int>>{\n'+''.join('  '+json.dumps(k)+': '+str(v)+',\n' for k,v in result.items())+'};\n')
report={'source':'https://ebible.org/Scriptures/eng-kjv_html.zip','sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'mapped_verses':len(result),'speech_parts_checked':phrases,'unmatched':unmatched,'rule':'Exact phrase match only; unmatched verses remain ordinary text pending review.'}
Path('tools/integrity/red_letter_import_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print({k:v for k,v in report.items() if k!='unmatched'}); print('Unmatched verses:',len(unmatched))
